service: serverless-web-app-sandbox
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: "3"

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-1

#functions:
#  awsCostNotifier:
#    handler: src/awsCostNotifier.handler
#    events:
#      - schedule: cron(0 0 * * ? *)
#    environment:
#      DISCORD_DEVELOP_WEBHOOK_URL: ${ssm:DISCORD_DEVELOP_WEBHOOK_URL}
